### ISSUE TITLE
Value lost in UploadField when collapsing/expanding the in-line form

### ISSUE THREAD

**Issue by MichelleZZZZ** [dnadesign/silverstripe-elemental#673]
SilverStripe CMS version: 4.3.1
dnadesign/silverstripe-elemental  4.0.2 
silverstripe/admin  1.3.1 

**Issue description:**
Upload a new image.
Save and publish.
Collapsed the elemental block.
The image go back to the previous one after reopen the in-line form.

Question:
Is there any new patch available to fix this?

**Comment by robbieaverill** [comment]
Have you tried using elemental 4.0.5?

**Comment by MichelleZZZZ** [comment]
Yes just changed to elemental 4.0.5, still having this issue.
---

dnadesign/silverstripe-elemental                  4.0.5              Elemental pagetype and collection of Elements
dnadesign/silverstripe-elemental-list             1.2.0              Adds a new element for nested elements
dynamic/silverstripe-elemental-accordion          2.0.2              Display content in collapsable panels
dynamic/silverstripe-elemental-baseobject         2.0.2              A simple base DataObject to use with Elemental Content Blocks
dynamic/silverstripe-elemental-blocks             3.0.1              A recipe to require additional elements for the SilverStri...
dynamic/silverstripe-elemental-blog               2.1.1              Show recent posts from a featured blog.
dynamic/silverstripe-elemental-countdown          2.0.3              Display a countdown to a specific date and time
dynamic/silverstripe-elemental-customer-service   2.0.4              Additional customer service element for the SilverStripe E...
dynamic/silverstripe-elemental-embedded-code      2.0.2              Embed code like iFrames or Javascript on a page.
dynamic/silverstripe-elemental-features           2.0.3              A block that displays featured content - large image, titl...
dynamic/silverstripe-elemental-filelist           2.0.1              A multi file block for SilverStripe Elemental
dynamic/silverstripe-elemental-flexslider         2.0.2              Flexslider slideshow content block for SilverStripe Elemental
dynamic/silverstripe-elemental-gallery            2.0.3              A block to display a collection of images
dynamic/silverstripe-elemental-image              2.0.1              A block to add a single image to your page.
dynamic/silverstripe-elemental-oembed             2.1.1              A block to embed media from other websites via oEmbed
dynamic/silverstripe-elemental-promos             2.0.2              A block to display a group of promo objects
dynamic/silverstripe-elemental-section-navigation 2.0.2              A block to display a list of links to child pages, or page...
dynamic/silverstripe-elemental-sponsors           2.0.1              Display a list of sponsor logos with links.
dynamic/silverstripe-elemental-tabset             2.0.1              Create a tabbed interface that uses elements
dynamic/silverstripe-elemental-testimonials       2.0.1              Testimonials element for the SilverStripe Elemental Module
silverstripe/admin                                1.3.1              SilverStripe admin interface

**Comment by jonom** [comment]
Made a screen recording to show this issue - it's a major UX problem I think. I have to save the page while the editing pane is open to get it to work, and even after that, the next time I open the pane the fields are blanked, despite the fact the content saved successfully. I'm also using 4.0.5. https://www.dropbox.com/s/8fvtzi5aolhxl3m/lost%20field%20state.mov?dl=0

**Comment by jonom** [comment]
Related: https://slackarchive.silverstripe.org/slack-archive/message/271080#msg_271080

**Comment by robbieaverill** [comment]
Thanks for the feedback everyone. @MichelleZZZZ have you tried using silverstripe/admin 1.3.3? I'm sure we fixed this problem recently...

**Comment by jonom** [comment]
@robbieaverill The same problem used to affect text fields and HTMLEditorFields but that doesn't seem to be happening to me anymore - text field values remain when UploadField values are blanked. So maybe the issue was mostly fixed but UploadFields are still experiencing it for some reason? I was using silverstripe/admin 1.3.3 when I recorded that video.

**Comment by robbieaverill** [comment]
I think https://github.com/silverstripe/silverstripe-asset-admin/issues/919 is one of the issues I was thinking of

**Comment by jonom** [comment]
Maybe this commit will fix it? https://github.com/silverstripe/silverstripe-asset-admin/pull/927/commits/595d8ec8bc11e102ab6ef3ec1cbb99e9d5c09cab it hasn't made it in to 1.3 stable yet

**Comment by jonom** [comment]
Yep. Changing my requirements to `"silverstripe/recipe-cms": "4.3.x-dev"` brought in `silverstripe/asset-admin 1.3.x-dev` and fixed the issue. I should have tried that earlier, sorry. 🙁

**Comment by michalkleiner** [comment]
Good case for speeding up patch releases when a fix is in.

**Comment by MichelleZZZZ** [comment]
@robbieaverill  Yup it is working with "silverstripe/recipe-cms": "4.3.x-dev" and "silverstripe/asset-admin 1.3.x-dev"
thanks for helping!

**Comment by jonom** [comment]
Looks like this issue can be closed. @robbieaverill going off topic here but do any repos besides Framework use a New Issue template? Just wondering how we could suggest/remind people (including myself) to test the latest / unreleased version of a module before opening an issue. [The docs](https://docs.silverstripe.org/en/4/contributing/issues_and_bugs/) have a brief mention about testing unreleased code but it would be easy to miss. If fixes were tagged right away it wouldn't be an issue but since it can take weeks for SS fixes to get released we should probably tell people to test the latest applicable dev branch rather than the latest release when verifying bugs.

**Comment by robbieaverill** [comment]
@jonom there's some discussions in framework around this kind of thing. See https://github.com/silverstripe/silverstripe-framework/issues/8343, https://github.com/silverstripe/silverstripe-framework/pull/8869, https://github.com/silverstripe/silverstripe-framework/pull/8347. At some point we'd hope that these contributing templates would be sync'd across all SilverStripe modules.

**Comment by robbieaverill** [comment]
Closing as this will be resolved in the next SilverStripe 4.3.x release. You can use 4.3.x-dev for asset-admin for now.
